apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:D2OHhkYug9TG0bU=,iv:fzS94YHmXlW5YPMbLSsY3deIEvBiVwQwIRqn+C2Ljpc=,tag:8v1IWzT4Vc2rljXgZAfcHQ==,type:str]
sops:
  age:
    - recipient: age1y2sy5juh3g7yqk3mwqsdqej3vzdwpctac2cwtk04vflhpfuujucs4qtuwr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwb05taFVNMDhjZHpWdjJs
        a0daVm5EWE1mbCsycXB2alZpRU8zbzJrdFdRCkdGQUl3OEkvdmJzWUd6b2l2R0Zh
        THpxU0pJUWxtNmVHVlB6eVRGQWFiNkEKLS0tIEg4UnJJM1BFOWFFbEs2eEpYKy9H
        dGZLcXRmNVA1OUxPejFXWmFCWE1aeFEKBM+SN23Xoab9SgILTBALtHAWXOD0xNET
        mheJn33bliNEjolGndux7IPKWr/HqrNrTUwRdJeQOdP9kEfPihiuAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-22T20:17:39Z"
  mac: ENC[AES256_GCM,data:MnxeEaTl6Y6DrdxuCS1UM8wReEBVdHwEUhY2xlWHtgSveycbZ/U+mHjHYQ/G6FIEftRSct97F4TqNTIFmwiQFfgnAmj8HIh4IRIjHcF8dgrfgLVjX5EeDkTjQ/AWRClsaPmWTH+amYyM7f1dfkAYFuZswDkgYzwNikcpN4TDAsg=,iv:wLGzdE3bgWc4kLbVKxYPTdstYlEPyTdwGiQJCmJfjw0=,tag:rkTtxLVYRh8AgwP1JHUK8A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
