apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:qEI2TiVrY2jn52U=,iv:Y3yQL0QNY5AJbnugjgP4/WUuimOPpChoHA4tiw3ez4Q=,tag:zRrXbEeLy2tW17CRQIX3OA==,type:str]
sops:
  age:
    - recipient: age1y2sy5juh3g7yqk3mwqsdqej3vzdwpctac2cwtk04vflhpfuujucs4qtuwr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOXJIUTdJL2JjWld5NmtK
        cEo0TjJWcHh4ZzhTaHNWNlpmVGJPNnNZZ0ZzCitjSXlLZkJiQm1hem5LSFIwNitP
        NkRYQW1kUmJ5Q1k0NUZiOUp2d2RnVGcKLS0tIDBIMFVMNXpzUHpJWTNtWWdRQXlq
        SG55K2F3ZUU2dEZRYjdLTzE4eWlkMGcKyIw73yVZbr6bZ5/dk6oYeOatPvuONbWo
        M+vApiQ8ZdeQ18maAIjTFVLoFSXS+55VaROE1brPbGQjnK6Vjfodtw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-22T20:11:04Z"
  mac: ENC[AES256_GCM,data:TdtrKRQ+1nXyl0KA5pUaMcyVPdK6OUi0fSMGKU26oX1Y6f74LoOkWD7gr8XSXyDu0Un2gpONVV/n0Hjxb0SoURiau8dSCl4qSBndpzufojqWXajhKYqDjQzPu3lilanz1sIvIW9slc06IarjDLGBwBALV8oGfegtS6N8kbzJDys=,iv:KhL/s315+7TnJ2zg09fsidhhNlhM0c1Wf2t+AnEcmeo=,tag:/gG96Rpzd93NmyInVWmvHA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
