apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:JM70eYK8uqh9rMENcR4ydo60ugviQE4kcxn8EWio1Bk=,iv:5G5XuLpaTnaV/ERVztVNAz4b2rDU2DEqj0urzzk2Co8=,tag:LtYLsVwp+sd0OsHhhXqM6g==,type:str]
sops:
  age:
    - recipient: age1y2sy5juh3g7yqk3mwqsdqej3vzdwpctac2cwtk04vflhpfuujucs4qtuwr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRmtXZklpdDdzNE8xQzBU
        UUk5Zjl1M21UZkZyQVl5R1pLNXd1Q0FrWnhVCmF4Nm45S3ZFVThDSlVIMjM0b1lu
        dmgveXVrVnFjV1lmL1Fldm9GVm51NUUKLS0tIFJXMXRZNVNTeHZBYW91YnBCeDJY
        MmdCa1dWeERZc0F0ZER5enJzRElXRHcKRsLw62feCYMz+xq/fysfYDNbCdXbZNTT
        RilONfXafDT5YSKxxUEwyjv58ALMDak8y90ufep7dDwBBFKNeEPLEg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-22T20:17:39Z"
  mac: ENC[AES256_GCM,data:PtInXyU67O/yjyGWRL+PSkJ9oMrVvonKzZWshTIc0HGLJpxrKWvXeZN6Th95u5yrEXRtW2XMbT3hoTtGp5NdY8m3s6J/m0ZYKfOt98A92leBHg5YLP6FP4DjUhR0bqTQxbi9OZdI7/PdoFiiOLpHfXsgB0qeVBkTJGyLBDnmx4s=,iv:kcGjrqLFjwulwr0xjgObfT70T9aTF50a2KQBpqMSlew=,tag:OB37okS/D9NYmO6hdeHOkQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
