apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:a/7Gg8WgnfdOYX/I+63r5JkAp1gajxag0QCRjJelR6E=,iv:y3YVUVCkE78cQAKtnvZIyrYSha1CwwcLuCqgbjeHhZc=,tag:sFCKWvf8KLn3KbjKvKwWdA==,type:str]
sops:
  age:
    - recipient: age1y2sy5juh3g7yqk3mwqsdqej3vzdwpctac2cwtk04vflhpfuujucs4qtuwr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWnNyZVpNTUZzMWY2cHVH
        bC9VSHE3VGlEdGI2bzR5VzIwVFdtM0hvSWgwClk5UmZyaEE3MjVMT0NRdlluUjVj
        MDZ4MkR0OTNFVDNReldJc3RnTHFTN1EKLS0tIFVHU0kzYkMvaDloYzQ5UERoblhh
        bDRibzRlYXB6UEV4QTdYMS9IQ0ZCYm8KCZbL3/VLedqaIa49nJC2xGj/HSZCnCou
        pvaabM8tmGlCokpJIwNfuGMo/03ySLE9+LKVMGBi388iXSbRrEcGpA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-22T20:11:04Z"
  mac: ENC[AES256_GCM,data:guh5LGF6MizbOzqW4iR/fOFGYtFbF6PM/ddDm+SAfw/qyH12JfBAsAohzOntJI1Z7jg1yNmZ9sfZWX3/nFJubDmOXCtyD8vgBuR6zwtcZj6vs/3G98ZERXGiVMBuqxAxSJI/uSjqs5nshllPPn8bE/dFdSaEClUgZ/q7qo4SIW0=,iv:NPVZPnJgaPU0Hyws+4SNkqQoEPWqsO9w0Nrs6TccW6U=,tag:r566wK5j8z8bM5886QMy/A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
