apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:6do=,iv:MAhoACOBTheW+AVT8vSKxohO3/QcZKpaSUdJnj1uUfo=,tag:q98CKdMj/m5Q0E/elUiytQ==,type:str]
sops:
  age:
    - recipient: age1y2sy5juh3g7yqk3mwqsdqej3vzdwpctac2cwtk04vflhpfuujucs4qtuwr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyek10Mm83bFZTcVE5NjhZ
        ekRvOUx6WkdkWnhQcE5iR3lBOHBTdzNqUUJFCnhNVHN6Ync2WXh3WmJZT2ZISGFr
        Snl2VHFLWFFwRGJQL0RHR1cxcGdwWFEKLS0tIFVQK0dMRjlDSDNyYkVKVUNQemU0
        aDZqY3lGdGV6YUdrR0pnTWRsMTl1L1kKmEp5KO6zlZRmPDjxupvYZKHJ61kRXCBo
        21h793kSYXn94b8KiLOYQV8iE3Vm8kSUaaUm+oU2op/FfbAu7YJNdw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-22T20:11:04Z"
  mac: ENC[AES256_GCM,data:yQcg4jLcdYrCDzPX3cuDR0QxaJo6/DomzlhAlDOQT6bpSR0OqOM7q2HoQF/vHNfSrzHqFUvV+Orbdet3ndjpmvmegqK9KnyltuRAt6jgi23YAZgwz2zEko6C7M3B+1POXnk3QemGjgV1lvBBb+TyVWanOQYXzzURE/FGn48ejdU=,iv:MmRSxiV6bRXsYD34gfYrn59JPQ+XXyTrVeeb1g7EXzY=,tag:Xl6s0Txz+BMRjHw2sSqJWQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
