apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:FlQ=,iv:NvCqz1eBVroGF/7H+I6yffxHjTxtkQeTCpkM7TKT+Co=,tag:W6/1KBZArPuX6x1BOd2MvQ==,type:str]
sops:
  age:
    - recipient: age1y2sy5juh3g7yqk3mwqsdqej3vzdwpctac2cwtk04vflhpfuujucs4qtuwr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTFdGT3hHRjRPdS9ZWjJw
        Nk9JYjZNWlUzV1pmMmlLN1FSdFllYWxPcmx3CjdpV3ZiNzM5dWxibzV6akd2OGhW
        UVNkZVVJQURjaWVGQ3I4ajZrZ20rK28KLS0tIGlIM2VyZE9BcEVQQVJ5Nnd0QjNj
        TXV6NzNXR0hORFBTMFNIK1Z1VVJkM3MKODzVSwJrWH/9au0LA6kifs9jU8/H0CYC
        oAupTzJRw76yBSbvK6E8ij9ddZfEefkAt4EO9hZIMMzhwP4Vry5fXg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-22T20:17:39Z"
  mac: ENC[AES256_GCM,data:DoVyxgc4XBrQIa0DCoVkgadK2qthTrL/CzpViZHFXNfHqXT3nCC+VT/KATWwX7xmfqRV9vC9vOM4wC2y+XBn9UhF3DkKkXh0dCHy4zdxf/N4kxGCS/UzOBldMxxXlFchuZVm7BRAN5KRHgkT6xm6oOMyA2MIKK2jpmKzV1vkB/c=,iv:MzsYZmTf5zswgaYvq4Tw4fnlkVH5Rs51U5iR1LfrC7c=,tag:7NhpPJXUK8jEnerwgQnHBg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
